#!/bin/bash
# description: Tomcat Start Stop Restart Status
# processname: tomcat
# chkconfig: 234 20 80

JAVA_HOME=/opt/jdk1.8.0_151
export JAVA_HOME
#PATH=$JAVA_HOME/bin:$PATH
#export PATH
CATALINA_HOME=/opt/tomcat7/apache-tomcat-7.0.82

case $1 in
start)
sh $CATALINA_HOME/bin/startup.sh
;;
stop)
sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
sh $CATALINA_HOME/bin/shutdown.sh
sh $CATALINA_HOME/bin/startup.sh
;;
status)
ps -ef | grep tomcat
esac
exit 0
